name: BTMC Gold Crawler

on:
  schedule:
    - cron: '0 2,11 * * *'   # 9h và 18h VN = 2h & 11h UTC
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run crawler
        env:
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: python crawler.py
